### ISSUE TITLE
Related list embed?

### ISSUE THREAD

**Issue by joefolds5** [anthonywong555/Twilio-SendGrid-Salesforce-Demo#1]
Hi, this looks great and is super useful. Thank you. One question, would it be possible to adapt to also embed a related list into the sendgrid email. e.g. send over the related list details from Salesforce and render within a dynamic Sendgrid template?  Thanks in advance if you can shed any light!

**Comment by anthonywong555** [comment]
Hi Joe. It's possible, but it would take some development effort; you would need to build a Salesforce Flow or LWC component.
